# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SixtApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SixtApp
  pod 'Moya'
  pod 'Moya-ObjectMapper/RxSwift'
  pod 'Kingfisher'
  pod 'RxCocoa'
  pod 'SVProgressHUD'
pod 'SDWebImage/MapKit'
end
